### ISSUE TITLE
start and end range values

### ISSUE THREAD

**Issue by d-salgado** [progenetix/bycon#1]
Hi,
I am wondering if in this query:
https://bycon.progenetix.org/query?datasetIds=arraymap&assemblyId=GRCh38&includeDatasetResponses=ALL&requestType=variantCNVrequest&referenceName=9&variantType=DEL&start=20000000&start=21975097&end=21967753&end=23000000&filters=icdom-94403
it will not be easier instead of duplicating the "Start" and "End" properties (to define a range for a region of interest) to have only one attribute "Start" or "End" with a range definition with a comma as following:
https://bycon.progenetix.org/query?datasetIds=arraymap&assemblyId=GRCh38&includeDatasetResponses=ALL&requestType=variantCNVrequest&referenceName=9&variantType=DEL&start=20000000,21975097&end=21967753,23000000&filters=icdom-94403
All the best
David

**Comment by mbaudis** [comment]
@d-salgado That is a method frequently being used, to treat all parameters as single value and then split them server-side, on an agreed character (mostly `,`); and we actually had done this as fallback in most implementations (all parameters are interpreted as potential lists, comma-concatenated and then comma-split; so all become arrays).
But the correct way (IMO) is to define which parameters are arrays in the specification and then interpret them accordingly when parsing the request (e.g. retrieving using `getValue` or `getList` or similar.
Apart from that Beacon v2 moves (slowly?) to POST requests with JSON messages, which obviates these points.
Summary: Comma-concatenating request values is a widespread "hack" that doesn't translate well into specifications.

**Comment by d-salgado** [comment]
@mbaudis Thank you I agree with you, this is difficult to translate into spec as it is today, but specs clearly distinguish start/end  and min/max. I believe it is valuable to gather min and max in an array as you have done in your description. That will be facilitated when key and values will be passed as json. However, I believe this is not good practices to have two url parameters keys with the same key name. It is the same as having in a HTML page two input fields with the same name or id.

**Comment by mbaudis** [comment]
@david Coming back to this: The definition which value is a list is handled by the specification. The [current for Beacon v2](https://github.com/ga4gh-beacon/specification-v2/blob/master/beacon.yaml#L896) says:

```json
        start:
          description: |
            Precise or fuzzy start coordinate position(s), allele locus 
            (0-based, inclusive).
            * `start` only:
              - for single positions, e.g. the start of a specified sequence 
              alteration where the size is given through the specified 
              `alternateBases`
              - typical use are queries for SNV and small InDels
              - the use of `start` without an `end` parameter requires the use 
              of `referenceBases`
            * `start` and `end`:
              - if used with `variantType`, for special use case for exactly 
              determined structural changes
              - without `variantType`, for searching any variant falling within 
              this range (a.k.a. range query)
            * use 2 values for querying imprecise positions (e.g. identifying 
            all structural variants starting anywhere between `start[0]` <-> 
            `start[1]`, and ending anywhere between `end[0]` <-> `end[1]`)
            * single or double sided precise matches 
            can be achieved by setting `start[1]=start[0]+1` and `end[1]=end[0]+1`
          type: array
          items:
            type: integer
            format: int64
          minimum: 0
          minItems: 1
          maxItems: 2
```
... which is basically my proposal from 2016 (which wasn't implemented in the Beacon v1 spec due to legacy concerns). So, following the spec:
* your server will know to retrieve `start` as an array (e.g. through `startVar = getlist("start")` in Python `cgi.FieldStorage()`
* the server implementation then has to either use the `len(startVar) == 1` or such to decide it is an exact match, or (smarter)
```python
if len(startVar) == 1:
    startVar.append(startVar[0]+1)
```
... which will allow to use interbase interval searches (`gteq startVar[0] && lt startVar[-1]`) to match single base positions, same as for larger intervals

**Comment by mbaudis** [comment]
Closing this since discussion has moved on for v2 etc.
