### ISSUE TITLE
VCF4.4

### ISSUE THREAD

**Issue by d-salgado** [progenetix/bycon#15]
Hello, 
Genome version should be indicated in the VCF for a specific dataset output
David

**Comment by mbaudis** [comment]
@d-salgado Always nice to post the "how it should look like" if known `¯\_(ツ)_/¯`

**Comment by mbaudis** [comment]
... addressed in https://github.com/progenetix/bycon/commit/a0f154567905aadc0939f13dab947bb477b01381

**Comment by mbaudis** [comment]
Done.
