### ISSUE TITLE
Optimize loading

### ISSUE THREAD

**Issue by mbaudis** [progenetix/bycon#2]
The `services` app is a loader / redirect for a most of the bycon apps, thereby guaranteeing stable paths etc.

One problem with this approach is that all the apps are loaded as packages, not only the called one:

https://github.com/progenetix/bycon/blob/23d89757bc0900cd3c71f8ac477db5e86c265f00/bin/services.py#L12

TODO: implement a dynamic loader, which only loads the selected package (after https://github.com/progenetix/bycon/blob/23d89757bc0900cd3c71f8ac477db5e86c265f00/bin/services.py#L75).

**Comment by KyleGao** [comment]
Can you give me a good testing example of the "REQUEST_URI"?

**Comment by mbaudis** [comment]
See in the head of the file; e.g. <https://progenetix.org/services/cytomapper/?assemblyId=ncbi36.1&cytoBands=8q&text=1>. The URL is split & the first part after "services" becomes the name of the called package/app. So the `services` app should just contain a list of allowed services & then load if matched, instead of loading everything which makes it very slow.

**Comment by KyleGao** [comment]
I have put up the dynamic loadings, however, I have a few concerns:

1. Modules are cached in Python, so when a package is repeatedly loaded, it only has a minor performance impact (table lookup, lock & unlock). Only in some special circumstances, repeated loading could have some sensible impacts. 
2. For the services, my understanding is that they will all be loaded sooner or later when the website is up. So dynamic loading may not save much. But I may be totally wrong, not an expert of web-dev. 

Anyway, at least the dynamic loading won't be slower than the lazy loading.

**Comment by mbaudis** [comment]
Thanks! My main concern is "tidyness"; it just makes more sense to have this handled by a simple configuration...

Michael
